// Mocks generated by Mockito 5.4.6 from annotations
// in what_on_earth/test/unit/tle_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:what_on_earth/position/tle_manager.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [TleManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockTleManager extends _i1.Mock implements _i2.TleManager {
  MockTleManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<String> get tleUpdates => (super.noSuchMethod(
        Invocation.getter(#tleUpdates),
        returnValue: _i3.Stream<String>.empty(),
      ) as _i3.Stream<String>);

  @override
  _i3.Future<void> fetchAndStore() => (super.noSuchMethod(
        Invocation.method(
          #fetchAndStore,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String?> loadStored() => (super.noSuchMethod(
        Invocation.method(
          #loadStored,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<DateTime?> lastFetchTime() => (super.noSuchMethod(
        Invocation.method(
          #lastFetchTime,
          [],
        ),
        returnValue: _i3.Future<DateTime?>.value(),
      ) as _i3.Future<DateTime?>);
}
